/**
  ******************************************************************************
  * @file      syscalls.c
  * @author    Auto-generated by STM32CubeIDE
  * @brief     Minimal STDIO syscalls for newlib-nano.
  *            _write is implemented in main.c (routes printf to USART1).
  ******************************************************************************
  */

#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <signal.h>

extern int _close(int file);
extern int _fstat(int file, struct stat *st);
extern int _isatty(int file);
extern int _lseek(int file, int ptr, int dir);
extern int _read(int file, char *ptr, int len);
extern int _kill(int pid, int sig);
extern int _getpid(void);

int _close(int file)
{
  (void)file;
  return -1;
}

int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file)
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _read(int file, char *ptr, int len)
{
  (void)file;
  (void)ptr;
  (void)len;
  return 0;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

int _getpid(void)
{
  return 1;
}
