/**
  ******************************************************************************
  * @file      sysmem.c
  * @author    Auto-generated by STM32CubeIDE
  * @brief     _sbrk() implementation for newlib-nano's malloc (used by libc,
  *            not by FreeRTOS - the FreeRTOS heap is the separate heap_4.c
  *            array sized by configTOTAL_HEAP_SIZE).
  ******************************************************************************
  */

#include <errno.h>
#include <stdint.h>

extern uint8_t _end;
extern uint8_t _estack;
extern uint32_t _Min_Stack_Size;

static uint8_t *__sbrk_heap_end = NULL;

void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end;
  static uint8_t *heap_end;
  uint8_t *prev_heap_end;

  if (heap_end == NULL)
  {
    heap_end = &_end;
  }

  prev_heap_end = heap_end;

  uint8_t *stack_limit = (uint8_t *)((uint32_t)&_estack - (uint32_t)&_Min_Stack_Size);
  if (heap_end + incr > stack_limit)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  heap_end += incr;
  (void)__sbrk_heap_end;
  return (void *)prev_heap_end;
}
